# This is the same as [general.import]
[general]
import = [ "catppuccin-mocha.toml" ]

[terminal.shell]
program = "/usr/bin/fish"

[window]
padding = { x = 10, y = 10 }
dimensions = { columns = 130, lines = 40 }

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 11

[keyboard]
bindings = [

{ mode = "Vi", mods = "Control", key = "L", action = "Last" },
{ mode = "Vi", mods = "Control", key = "H", action = "First" },
{ mode = "Vi", mods = "Shift", key = "Slash", action = "SearchForward" },

]
